import type { AiFloorProfile } from './types';

export const AI_FLOOR_PROFILES: readonly AiFloorProfile[] = [
  {
    floor: 1,
    reactionTicks: 48,
    lookahead: 0,
    topK: 5,
    rankWeights: [0.2, 0.2, 0.2, 0.2, 0.2],
    futureDiscount: 0,
    weights: {
      aggregateHeight: -0.25,
      maxHeight: -0.5,
      holes: -2,
      bumpiness: -0.25,
      clearedLines: 0.8,
      combo: 0.3,
      incomingOffset: 0.4,
      itemGain: 0.5,
      opponentPressure: 0,
    },
    itemPolicy: 'FIRST_VALID',
  },
  {
    floor: 2,
    reactionTicks: 27,
    lookahead: 1,
    topK: 3,
    rankWeights: [0.6, 0.3, 0.1],
    futureDiscount: 0.65,
    weights: {
      aggregateHeight: -0.35,
      maxHeight: -0.8,
      holes: -3.5,
      bumpiness: -0.45,
      clearedLines: 1.2,
      combo: 0.9,
      incomingOffset: 1.1,
      itemGain: 1.2,
      opponentPressure: 0.2,
    },
    itemPolicy: 'RISK_AWARE',
  },
  {
    floor: 3,
    reactionTicks: 12,
    lookahead: 2,
    topK: 1,
    rankWeights: [1],
    futureDiscount: 0.7,
    weights: {
      aggregateHeight: -0.45,
      maxHeight: -1.2,
      holes: -5,
      bumpiness: -0.65,
      clearedLines: 1.5,
      combo: 1.8,
      incomingOffset: 1.8,
      itemGain: 1.5,
      opponentPressure: 0.6,
    },
    itemPolicy: 'TACTICAL',
  },
];
